# Generated by Django 6.0.7 on 2026-07-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_email_verified_and_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
    ]
