services:
  - type: web
    name: printhub
    env: python
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='superadmin').exists() or User.objects.create_superuser('superadmin', 'scholargrant22@gmail.com', 'Ihategoogle@12')"
      python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.9"
