# Generated by Django 6.0.7 on 2026-07-22 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_collected_at_order_printing_at_order_ready_at'),
        ('stations', '0002_seed_stations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paused', models.BooleanField(default=False)),
                ('pause_reason', models.CharField(blank=True, default='', max_length=255)),
                ('total_paused_seconds', models.FloatField(default=0.0)),
                ('pause_started_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='agent_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission paid to agent', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='binding',
            field=models.CharField(choices=[('none', 'No Binding'), ('staple', 'Staple (Corner)'), ('spiral', 'Spiral Binding')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for cancellation'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cost_of_goods',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of paper used', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Pickup at Station'), ('delivery', 'Deliver to Me')], default='pickup', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='in_transit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Internal notes about this order'),
        ),
        migrations.AddField(
            model_name='order',
            name='paper_used',
            field=models.IntegerField(default=0, help_text='Number of physical sheets consumed'),
        ),
        migrations.AddField(
            model_name='order',
            name='postponed_minutes',
            field=models.IntegerField(default=0, help_text='Extra minutes added if the order is postponed.'),
        ),
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Net profit for this order', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='sla_minutes',
            field=models.IntegerField(default=120, help_text='Target time to complete order in minutes.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('printing', 'Printing'), ('in_transit', 'In Transit'), ('ready', 'Ready for Pickup'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Main Campus, City Center', max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_fee', models.IntegerField(default=0, help_text='Delivery fee in UGX')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='orders_deli_is_acti_486a82_idx')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.deliveryzone'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['station', 'status'], name='orders_orde_station_2a2238_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'created_at'], name='orders_orde_client__8a22e4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
    ]
