# Generated by Django 6.0.7 on 2026-07-30 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_file_metadata'),
        ('stations', '0002_seed_stations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Announcement', max_length=200)),
                ('message', models.TextField(help_text='Message to display in the announcement bar')),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_home', models.BooleanField(default=True, help_text='Show on homepage')),
                ('background_color', models.CharField(default='bg-blue-600', help_text='Tailwind class: bg-blue-600, bg-red-600, bg-green-600, bg-purple-600, bg-orange-600, etc.', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='copies',
            field=models.IntegerField(default=1, help_text='Number of copies to print'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('document', 'Document Print'), ('passport', 'Passport Photo'), ('scanned', 'Scanned Document')], default='document', help_text='Type of print order (document, passport photo, or scanned document)', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='paper_size',
            field=models.CharField(choices=[('A4', 'A4'), ('4x6', '4x6 (Passport)'), ('2x2', '2x2 (Passport)')], default='A4', help_text='Paper size for printing', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='referral_discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied from referral bonuses', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type'], name='orders_orde_order_t_d697ad_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['copies'], name='orders_orde_copies_a1ba50_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paper_size'], name='orders_orde_paper_s_1e0498_idx'),
        ),
    ]
