# Generated by Django 6.0.7 on 2026-07-30 05:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_announcement_order_copies_order_order_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money')], max_length=10, unique=True)),
                ('merchant_name', models.CharField(max_length=100)),
                ('merchant_phone', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Merchant Setting',
                'verbose_name_plural': 'Merchant Settings',
            },
        ),
        migrations.CreateModel(
            name='PaperInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(choices=[('A4_white', 'A4 White (80gsm)'), ('A4_colored', 'A4 Colored'), ('A3_white', 'A3 White (80gsm)'), ('A3_colored', 'A3 Colored'), ('legal', 'Legal Size'), ('photo', 'Photo Paper')], default='A4_white', max_length=50)),
                ('quantity', models.IntegerField(default=0, help_text='Number of sheets in stock', validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_per_sheet', models.DecimalField(decimal_places=2, help_text='Cost per sheet in UGX', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('low_stock_threshold', models.IntegerField(default=500, help_text='Alert when stock falls below this number')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True)),
                ('last_restocked_quantity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Paper Inventory',
                'ordering': ['paper_type'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_percentage', models.DecimalField(decimal_places=2, help_text='Commission percentage (e.g., 10.00 for 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commission_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission Rate',
                'verbose_name_plural': 'Commission Rates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order total to apply discount', max_digits=10)),
                ('max_uses', models.IntegerField(default=0, help_text='0 for unlimited')),
                ('used_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discount Code',
                'verbose_name_plural': 'Discount Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('paper', 'Paper & Supplies'), ('toner', 'Toner & Ink'), ('maintenance', 'Equipment Maintenance'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('salary', 'Salaries'), ('marketing', 'Marketing'), ('transport', 'Transport'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=500)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_earnings', to='orders.order')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Earning',
                'verbose_name_plural': 'Agent Earnings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'is_paid'], name='finances_ag_agent_i_138dd6_idx'), models.Index(fields=['created_at'], name='finances_ag_created_33cfe1_idx'), models.Index(fields=['status'], name='finances_ag_status_2237a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('commission', 'Commission Paid'), ('refund', 'Refund'), ('paper_purchase', 'Paper Purchase'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('paper', 'Paper & Supplies'), ('toner', 'Toner & Ink'), ('maintenance', 'Equipment Maintenance'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('salary', 'Salaries'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', help_text='Expense category (for expenses only)', max_length=20)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_financial_records', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financial_records', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='orders.order')),
            ],
            options={
                'verbose_name': 'Financial Record',
                'verbose_name_plural': 'Financial Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_type', 'created_at'], name='finances_fi_transac_944554_idx'), models.Index(fields=['created_at'], name='finances_fi_created_9c5244_idx'), models.Index(fields=['order'], name='finances_fi_order_i_f2e6be_idx'), models.Index(fields=['agent'], name='finances_fi_agent_i_4f79b3_idx')],
            },
        ),
    ]
